name: Sync NYSERDA Heating Oil Data

on:
  # Run every Monday at 9 AM UTC
  schedule:
    - cron: "0 9 * * 1"

  # Allow manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🛢️ Run data sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: python nyserda_xls_ingest.py

      - name: ✅ Success notification
        if: success()
        run: echo "Data sync completed successfully!"

      - name: ❌ Failure notification
        if: failure()
        run: echo "Data sync failed - check logs"
